# Utiliser l'image de base nginx:alpine
FROM nginx:alpine

# Copier le fichier de configuration nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copier le fichier de configuration du site
COPY default.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80
EXPOSE 80

# Commande de démarrage
CMD ["nginx", "-g", "daemon off;"]

